In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:

df = pd.read_csv("C:/Users/prolo/OneDrive/Desktop/Encryptic Internship/fraudTrain.csv")
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [4]:

df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [5]:

df.drop(columns=['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'first', 'last', 'street', 'city', 'state', 'zip', 'trans_num', 'unix_time', 'dob'], inplace=True)

df.columns

Index(['merchant', 'category', 'amt', 'gender', 'lat', 'long', 'city_pop',
       'job', 'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [6]:

df.head()

merchant       category     amt gender      lat  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97      F  36.0788   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23      F  48.8878   
2                fraud_Lind-Buckridge  entertainment  220.11      M  42.1808   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00      M  46.2306   
4                 fraud_Keeling-Crist       misc_pos   41.96      M  38.4207   

       long  city_pop                                job  merch_lat  \
0  -81.1781      3495          Psychologist, counselling  36.011293   
1 -118.2105       149  Special educational needs teacher  49.159047   
2 -112.2620      4154        Nature conservation officer  43.150704   
3 -112.1138      1939                    Patent attorney  47.034331   
4  -79.4629        99     Dance movement psychotherapist  38.674999   

   merch_long  is_fraud  
0  -82.048315         0  
1 -118.186462         0  
2 -112.154481         0  
3 -112.561071         0  
4  -78.632459         0

In [7]:
df = pd.get_dummies(df, columns=['merchant', 'category', 'gender', 'job'])

scaler = StandardScaler()
df['amt'] = scaler.fit_transform(df['amt'].values.reshape(-1,1))

In [8]:
X = df.drop('is_fraud', axis=1)
y = df['is_fraud']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [11]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
print(y_pred_lr)

[0 0 0 ... 0 0 0]


In [12]:
print("Logistic Regression")
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))
print("AUC-ROC:", roc_auc_score(y_test, y_pred_lr))

Logistic Regression
[[257815      0]
 [  1520      0]]


c:\Users\prolo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\prolo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\prolo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.99      1.00      1.00    257815
           1       0.00      0.00      0.00      1520

    accuracy                           0.99    259335
   macro avg       0.50      0.50      0.50    259335
weighted avg       0.99      0.99      0.99    259335

AUC-ROC: 0.5


In [13]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)
print(y_pred_dt)

[0 0 0 ... 0 0 0]


In [16]:
print("Decision Tree Classifier")
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))
print("AUC-ROC:", roc_auc_score(y_test, y_pred_dt))

Decision Tree Classifier
[[257387    428]
 [   505   1015]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    257815
           1       0.70      0.67      0.69      1520

    accuracy                           1.00    259335
   macro avg       0.85      0.83      0.84    259335
weighted avg       1.00      1.00      1.00    259335

AUC-ROC: 0.8330515263903022


In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
rft = RandomForestClassifier()
rft.fit(X_train, y_train)
y_predict_rft = rft.predict(X_test)
print(y_predict_rft)

In [ ]:
print("Random Forest Classifier")
print(confusion_matrix(y_test, y_predict_rft))
print(classification_report(y_test, y_predict_rft))
print("AUC-ROC:", roc_auc_score(y_test, y_predict_rft))